baseURL = "https://tulsaathleticsclub.com/"
languageCode = "en"
title = "Tulsa Athletics Club"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-37717223-8"

[params]
    title = "Tulsa Athletics Club"
    date = "2020-07-01"
    description = "Athletics team, distance running and athletic performance training for Tulsa, OK"
    images = ["/images/social-share.jpg"]
    email = "george.perry@austintrackclub.com"
    keywords = "athletics, track and field, jumping, running, throwing, high jump, long jump, pole vault, shot put, discus, hammer, javelin, sprints, hurdles, middle distance, distance running, tulsa"
    copyright = "copyright: Tulsa Athletics Club 2020"
    cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
    subscriptionUrl = "mailto:george.perry@austintrackclub.com"
    appleTouchIcon = "/sch apple touch icon.png"
    favicon32 = "/schfavicon32.png"
    favicon16 = "/schfavicon16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#162b49"

[params.logos]
    jumbo = "/images/tulsa ac front large.png"
    header = "/images/tulsa ac logo text blue.png"
    footer = "/images/tulsa ac logo text blue.png"

[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[[menu.main]]
  name="Home"
  url = "/"
  weight="-1"

[[menu.main]]
  name="Programs"
  url = ""
  weight="2"

    [[menu.main]]
      name="Athletics Performance"
      url = "/athletic-performance"
      parent = "Programs"
      weight="1"

    [[menu.main]]
      name="Distance running"
      url = "/distance-running"
      parent = "Programs"
      weight="1"

    [[menu.main]]
      name="Athletic Team"
      url = "/athletics-team"
      parent = "Programs"
      weight="1"

[[menu.main]]
  name="Coaches"
  url = "/coaches"
  weight="3"

[[menu.main]]
  name="Blog"
  url = "/blog"
  weight="4"
